name: docs-ci
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  lint-md:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: avto-dev/markdown-lint@v1
        with:
          config: ''
